language: cpp
compiler:
  - gcc
#  - clang
# Make sure CMake is installed
install:
 - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update >/dev/null
 - sudo apt-get -q install build-essential pkg-config protobuf-compiler libprotoc-dev libprotobuf7 libprotobuf-dev libosmpbf-dev libpng12-dev libbz2-dev libstxxl-dev libstxxl-doc libstxxl1 libxml2-dev libzip-dev lua5.1 liblua5.1-0-dev libluabind-dev libluajit-5.1-dev libtbb-dev
# - sudo apt-get -q install g++-4.8
 - sudo apt-get install libboost1.54-all-dev
 # luabind
# - curl https://gist.githubusercontent.com/DennisOSRM/f2eb7b948e6fe1ae319e/raw/install-luabind.sh | sudo bash
 # osmosis
# - curl -s https://gist.githubusercontent.com/DennisOSRM/803a64a9178ec375069f/raw/ | sudo bash
 # cmake
 - curl -s https://gist.githubusercontent.com/DennisOSRM/5fad9bee5c7f09fd7fc9/raw/ | sudo bash
 # osmpbf library
# - curl -s https://gist.githubusercontent.com/DennisOSRM/13b1b4fe38a57ead850e/raw/install_osmpbf.sh | sudo bash
before_script:
# - rvm use 1.9.3
# - gem install bundler
# - bundle install
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS
script:
 - make -j 2
# - make -j 2 tests
# - ./datastructure-tests
# - cd ..
# - cucumber -p verify
after_script:
# - cd ..
# - cucumber -p verify
branches:
  only:
    - master
#    - develop
cache:
- bundler
- apt
env:
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release OSRM_PORT=5000 OSRM_TIMEOUT=60
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug OSRM_PORT=5010 OSRM_TIMEOUT=60
notifications:
# irc:
#  channels:
#    - irc.oftc.net#osrm
#  on_success: change
#  on_failure: always
#  use_notice: true
#  skip_join: false

  recipients:
    - am_neggaz@esi.dz
  email:
    on_success: change
    on_failure: always
